[package]
edition = "2021"
name = "daily_coding_problem"
version = "1.0.0"

[[bin]]
name = "downloader"
path = "scripts/downloader.rs"

[[bin]]
name = "generate_readme"
path = "scripts/generate_readme.rs"

[dependencies]
pretty_assertions = "1.2"
rand = "0.8"
