name: Rust Fmt

on:
  push:
    branches:
      - main
    paths:
      - "src/problems/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/problems/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run format
        run: cargo fmt --verbose
      - name: Commit formatted changes
        run: |
          git config --global user.name 'Frazzer951'
          git config --global user.email 'luke343279@gmail.com'
          [[ -n $(git status -s) ]] && git commit -am "docs: format Files"
          git push
